#!/bin/bash
echo "-----------------------------------------------------"
echo "Administration de la machine "
echo "-----------------------------------------------------"
echo "1- Gestion des modules"
echo "2- Gestion de l'arret et du démarrage"
echo "3- Gestion des comptes et des groupes"
echo "4- Gestion des process"
echo "99- Quitter"
echo "-----------------------------------------------------"
read c 
echo c
case $c in 
1) echo "-----------------------------------------------------"
   echo "Modules"
   echo "11- Lister les modules" 
   echo "12- Effacer un module"
   echo "13- Insérer un module"
   echo "14- Revenir au menu précédant"
   echo "99- Quitter"
   read c1
   case $c1 in 
   11) lsmod 
	;;
   12) echo "Donner le nom du module à supprimer "
      read module 
      sudo rmmod $module 
	;;
   13) echo "Donner le nom du module à insérer"
      read module 
      sudo modprobe $module
	;;
   14) 5_administration
        ;;
   99) exit
        ;;
   esac
   5_administration   
  ;;
2) echo "-----------------------------------------------------"
   echo "Runlevels "
   echo "21- Arret de la machine"
   echo "22- Afficher le niveau d'exécution actuel "
   echo "23- Chagnger le niveau d'exécution "
   echo "24- Afficher le niveau d'exécution au démarrage par défaut"
   echo "25- Activer/stopper un service au démarrage ou arret"
   echo "26- Revenir au menu précédant "
   echo "99- Quitter"
   read c2 
   case $c2 in 
   21) init 0
       ;;
   22) who -r 
       ;;
   23) echo "Donner le niveau cible"
       read niveau 
       init $niveau 
       ;;
   25)  echo "-----------------------------------------------------"
	echo "Choisir le service à activer ou stopper "
        echo "1- networking"
	echo "2- bluetooth"        
        echo "3- keyboard "
        read choix 
        case $choix in 
        1) echo "-----------------------------------------------------"
	   echo "Merci de choisir "
           echo "1- Pour activer le service networking"
           echo "2- Pour stopper le service networking"
           echo "99- Quitter"
           read x
           case $x in 
           1) /etc/init.d/networking start
		;;
           2) /etc/init.d/networking stop
		;;
           99) exit 
		;;
	   esac 
       ;;
        2) echo "-----------------------------------------------------"
	   echo "Merci de choisir "
           echo "1- Pour activer le service bluetooth"
           echo "2- Pour stopper le service bluetooth"
           echo "99- Quitter"
           read x
           case $x in 
           1) /etc/init.d/bluetooth start
		;;
           2) /etc/init.d/bluetooth stop
		;;
           99) exit 
		;;
	   esac 
       ;;
        3) echo "-----------------------------------------------------"
	   echo "Merci de choisir "
           echo "1- Pour activer le service keyboard"
           echo "2- Pour stopper le service keyboard"
           echo "99- Quitter"
           read x
           case $x in 
           1)  echo "activation "
             /etc/init.d/keyboard-setup.sh start
		;;
           2) echo "stopping "
                /etc/init.d/keyboard-setup.sh stop
		;;
           99) exit 
		;;
	   esac 
        ;;
      esac 
       ;;
   26) 5_administration 
	;;
   99) exit 
    ;;
   esac
   5_administration   
  ;;
3) echo "-----------------------------------------------------"
   echo "Comptes et groupes"
   echo "31- Lister les comptes"
   echo "32- LIster les groupes"
   echo "33- Ajouter un compte"
   echo "34- Revenir au menu précédant"
   echo "99- Quitter"
   read c3 
   case $c3 in 
   31) cat /etc/passwd
      ;;
   32) cat /etc/group
      ;;
   33)	echo "Donner le nom de 'lutilisateur à ajouter"
	read username
	sudo useradd $username      
	;;
   34) 5_administration
 	;;
   99) exit 
	;;
   esac
  5_administration
;;
4) echo "-----------------------------------------------------"
   echo "Gestion des process"
   echo "41- Lister les process"
   echo "42- Tuer un process"
   echo "43- Suspendre un process"
   echo "44- Relancer un process"
   echo "45- Revenir au menu précédant"
   echo "99- Quitter"
   read c4
   case $c4 in 
   41) ps -ef 
	;;
   42) echo "Donner le nom du process à tuer "
      read process
      killall $process 
	;;
   43) echo "Donner le nom du process à suspendre"
      read nom
      pid=`ps -ef | tr -s " " | cut -d " " -f2,8 | grep $nom | cut -d " " -f1`
      kill -STOP $pid
	;;
   44)echo "Donner le nom du process à reprendre"
      read nom
      pid=`ps -ef | tr -s " " | cut -d " " -f2,8 | grep $nom | cut -d " " -f1`
      kill -CONT $pid
	;;
   45) 5_administration
	;;
   99) exit 
       ;;
   esac
   5_administration
;;
esac
